from pathlib import Path
import json
import unittest


ROOT = Path(__file__).resolve().parents[1]
GAME3D = ROOT / "game3d"


class TestGame3DScaffold(unittest.TestCase):
    def test_gitignore_has_generated_file_rules(self):
        gitignore = ROOT / ".gitignore"
        self.assertTrue(gitignore.exists(), "Missing file: .gitignore")
        content = gitignore.read_text(encoding="utf-8")
        self.assertIn("game3d/.godot/", content)
        self.assertIn("__pycache__/", content)
        self.assertIn("*.pyc", content)

    def test_required_files_exist(self):
        required = [
            GAME3D / "project.godot",
            GAME3D / "scenes" / "MainSandbox.tscn",
            GAME3D / "scripts" / "core" / "GameLoop.gd",
            GAME3D / "scripts" / "world" / "WorldManager.gd",
            GAME3D / "scripts" / "entities" / "Actor.gd",
            GAME3D / "scripts" / "entities" / "HumanAgent.gd",
            GAME3D / "scripts" / "entities" / "MonsterAgent.gd",
            GAME3D / "scripts" / "entities" / "BruteMonster.gd",
            GAME3D / "scripts" / "entities" / "RangedMonster.gd",
            GAME3D / "scripts" / "ai" / "AgentAI.gd",
            GAME3D / "scripts" / "combat" / "CombatSystem.gd",
            GAME3D / "scripts" / "magic" / "MagicSystem.gd",
            GAME3D / "scripts" / "sandbox" / "SandboxSystems.gd",
            GAME3D / "scripts" / "data" / "DataLoader.gd",
            GAME3D / "scripts" / "ui" / "DebugOverlay.gd",
        ]

        for path in required:
            self.assertTrue(path.exists(), f"Missing file: {path}")

    def test_creature_profiles_json_exists_and_has_expected_ids(self):
        shared_path = ROOT / "shared_data" / "creatures.json"
        godot_path = GAME3D / "data" / "creatures.json"
        self.assertTrue(shared_path.exists(), f"Missing file: {shared_path}")
        self.assertTrue(godot_path.exists(), f"Missing file: {godot_path}")

        payload = json.loads(godot_path.read_text(encoding="utf-8"))
        profiles = payload.get("profiles", [])
        self.assertIsInstance(profiles, list)

        ids = {entry.get("id") for entry in profiles if isinstance(entry, dict)}
        expected_ids = {
            "human_fighter",
            "human_mage",
            "human_scout",
            "monster_standard",
            "monster_brute",
            "monster_ranged",
        }
        self.assertTrue(expected_ids.issubset(ids))

    def test_world_events_json_exists_and_has_expected_ids(self):
        shared_path = ROOT / "shared_data" / "events.json"
        godot_path = GAME3D / "data" / "events.json"
        self.assertTrue(shared_path.exists(), f"Missing file: {shared_path}")
        self.assertTrue(godot_path.exists(), f"Missing file: {godot_path}")

        payload = json.loads(godot_path.read_text(encoding="utf-8"))
        events = payload.get("events", [])
        self.assertIsInstance(events, list)

        ids = {entry.get("id") for entry in events if isinstance(entry, dict)}
        expected_ids = {"mana_surge", "monster_frenzy", "sanctuary_calm"}
        self.assertTrue(expected_ids.issubset(ids))

    def test_faction_templates_json_exists_and_has_expected_ids(self):
        shared_path = ROOT / "shared_data" / "factions.json"
        godot_path = GAME3D / "data" / "factions.json"
        self.assertTrue(shared_path.exists(), f"Missing file: {shared_path}")
        self.assertTrue(godot_path.exists(), f"Missing file: {godot_path}")

        payload = json.loads(godot_path.read_text(encoding="utf-8"))
        factions = payload.get("factions", [])
        self.assertIsInstance(factions, list)

        ids = {entry.get("id") for entry in factions if isinstance(entry, dict)}
        expected_ids = {"human_core", "monster_core"}
        self.assertTrue(expected_ids.issubset(ids))

    def test_doctrine_templates_json_exists_and_has_expected_ids(self):
        shared_path = ROOT / "shared_data" / "doctrines.json"
        godot_path = GAME3D / "data" / "doctrines.json"
        self.assertTrue(shared_path.exists(), f"Missing file: {shared_path}")
        self.assertTrue(godot_path.exists(), f"Missing file: {godot_path}")

        payload = json.loads(godot_path.read_text(encoding="utf-8"))
        doctrines = payload.get("doctrines", [])
        self.assertIsInstance(doctrines, list)

        ids = {entry.get("id") for entry in doctrines if isinstance(entry, dict)}
        expected_ids = {"warlike", "steadfast", "arcane"}
        self.assertTrue(expected_ids.issubset(ids))

    def test_relic_templates_json_exists_and_has_expected_ids(self):
        shared_path = ROOT / "shared_data" / "relics.json"
        godot_path = GAME3D / "data" / "relics.json"
        self.assertTrue(shared_path.exists(), f"Missing file: {shared_path}")
        self.assertTrue(godot_path.exists(), f"Missing file: {godot_path}")

        payload = json.loads(godot_path.read_text(encoding="utf-8"))
        relics = payload.get("relics", [])
        self.assertIsInstance(relics, list)

        ids = {entry.get("id") for entry in relics if isinstance(entry, dict)}
        expected_ids = {"arcane_sigil", "oath_standard"}
        self.assertTrue(expected_ids.issubset(ids))

    def test_location_templates_json_exists_and_has_expected_ids(self):
        shared_path = ROOT / "shared_data" / "locations.json"
        godot_path = GAME3D / "data" / "locations.json"
        self.assertTrue(shared_path.exists(), f"Missing file: {shared_path}")
        self.assertTrue(godot_path.exists(), f"Missing file: {godot_path}")

        payload = json.loads(godot_path.read_text(encoding="utf-8"))
        locations = payload.get("locations", [])
        self.assertIsInstance(locations, list)

        ids = {entry.get("id") for entry in locations if isinstance(entry, dict)}
        expected_ids = {"camp", "ruins", "rift_gate"}
        self.assertTrue(expected_ids.issubset(ids))

    def test_data_loader_is_hooked_in_game_loop(self):
        game_loop = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("DataLoaderScript", game_loop)
        self.assertIn("_load_creature_profiles_data", game_loop)
        self.assertIn("_load_world_events_data", game_loop)
        self.assertIn("_load_faction_templates_data", game_loop)
        self.assertIn("_load_doctrine_templates_data", game_loop)
        self.assertIn("_load_location_templates_data", game_loop)
        self.assertIn("_load_relic_templates_data", game_loop)
        self.assertIn("DataLoader OK", game_loop)
        self.assertIn("DataLoader OK: world events", game_loop)
        self.assertIn("DataLoader OK: faction templates", game_loop)
        self.assertIn("DataLoader OK: doctrine templates", game_loop)
        self.assertIn("DataLoader OK: location templates", game_loop)
        self.assertIn("DataLoader OK: relic templates", game_loop)

        sandbox = (GAME3D / "scripts" / "sandbox" / "SandboxSystems.gd").read_text(encoding="utf-8")
        self.assertIn("set_creature_profiles", sandbox)
        self.assertIn("_apply_profile_to_actor", sandbox)

        data_loader = (GAME3D / "scripts" / "data" / "DataLoader.gd").read_text(encoding="utf-8")
        self.assertIn("load_world_events", data_loader)
        self.assertIn("get_world_events", data_loader)
        self.assertIn("load_faction_templates", data_loader)
        self.assertIn("get_faction_templates", data_loader)
        self.assertIn("load_doctrine_templates", data_loader)
        self.assertIn("get_doctrine_templates", data_loader)
        self.assertIn("load_location_templates", data_loader)
        self.assertIn("get_location_templates", data_loader)
        self.assertIn("load_relic_templates", data_loader)
        self.assertIn("get_relic_templates", data_loader)

    def test_project_targets_main_scene(self):
        content = (GAME3D / "project.godot").read_text(encoding="utf-8")
        self.assertIn('run/main_scene="res://scenes/MainSandbox.tscn"', content)

    def test_main_scene_wires_core_systems(self):
        content = (GAME3D / "scenes" / "MainSandbox.tscn").read_text(encoding="utf-8")
        required_fragments = [
            "scripts/core/GameLoop.gd",
            "scripts/world/WorldManager.gd",
            "scripts/combat/CombatSystem.gd",
            "scripts/magic/MagicSystem.gd",
            "scripts/sandbox/SandboxSystems.gd",
            "scripts/ui/DebugOverlay.gd",
        ]
        for fragment in required_fragments:
            self.assertIn(fragment, content)

    def test_readme_mentions_new_3d_direction(self):
        content = (ROOT / "README.md").read_text(encoding="utf-8").lower()
        self.assertIn("game3d", content)
        self.assertIn("legacy python", content)
        self.assertIn("poi", content)
        self.assertIn("nova", content)
        self.assertIn("brute", content)
        self.assertIn("ranged", content)
        self.assertIn("control", content)
        self.assertIn("slow", content)
        self.assertIn("fighter", content)
        self.assertIn("mage", content)
        self.assertIn("scout", content)
        self.assertIn("champion", content)
        self.assertIn("rally", content)
        self.assertIn("outpost", content)
        self.assertIn("lair", content)
        self.assertIn("structure", content)
        self.assertIn("raid", content)
        self.assertIn("allegiance", content)
        self.assertIn("world event", content)
        self.assertIn("mana surge", content)
        self.assertIn("monster frenzy", content)
        self.assertIn("sanctuary calm", content)
        self.assertIn("special arrival", content)
        self.assertIn("summoned hero", content)
        self.assertIn("calamity invader", content)
        self.assertIn("relic", content)
        self.assertIn("arcane sigil", content)
        self.assertIn("oath standard", content)
        self.assertIn("bounty", content)
        self.assertIn("marked target", content)
        self.assertIn("hunt", content)
        self.assertIn("renown", content)
        self.assertIn("notoriety", content)
        self.assertIn("rift gate", content)
        self.assertIn("dungeon/gate", content)
        self.assertIn("gate response", content)
        self.assertIn("gate_seal", content)
        self.assertIn("gate_exploit", content)
        self.assertIn("allegiance crisis", content)
        self.assertIn("recovery pulse", content)
        self.assertIn("doctrine", content)
        self.assertIn("ethos", content)
        self.assertIn("project", content)
        self.assertIn("fortify", content)
        self.assertIn("warband", content)
        self.assertIn("ritual", content)
        self.assertIn("vendetta", content)
        self.assertIn("grudge", content)
        self.assertIn("legacy", content)
        self.assertIn("succession", content)
        self.assertIn("successor", content)
        self.assertIn("memorial", content)
        self.assertIn("scar", content)
        self.assertIn("destiny", content)
        self.assertIn("convergence", content)
        self.assertIn("sanctified", content)
        self.assertIn("corrupted", content)
        self.assertIn("rivalry", content)
        self.assertIn("duel", content)
        self.assertIn("bond", content)
        self.assertIn("patron", content)
        self.assertIn("splinter", content)
        self.assertIn("breakaway", content)
        self.assertIn("mending", content)
        self.assertIn("reconciliation", content)
        self.assertIn("oath", content)
        self.assertIn("sworn", content)
        self.assertIn("echo", content)
        self.assertIn("aftershock", content)
        self.assertIn("expedition", content)
        self.assertIn("pilgrimage", content)
        self.assertIn("alert pulse", content)
        self.assertIn("watch", content)
        self.assertIn("sanctuary_site", content)
        self.assertIn("dark_bastion", content)
        self.assertIn("taboo", content)
        self.assertIn("forbidden_site", content)
        self.assertIn("cursed_warning", content)
        self.assertIn("run narrative summary", content)
        self.assertIn("run result", content)
        self.assertIn("run restart", content)
        self.assertIn("plusieurs objectifs", content)
        self.assertIn("objectif actif par defaut", content)
        self.assertIn("run_status", content)
        self.assertIn("objective_status", content)
        self.assertIn("world objective", content)
        self.assertIn("objective_fail_reason", content)
        self.assertIn("objective_elapsed", content)
        self.assertIn("objective_required", content)
        self.assertIn("objective_switch_count", content)
        self.assertIn("too_many_deaths", content)
        self.assertIn("dominance_too_unstable", content)
        self.assertIn("observe_dominance", content)
        self.assertIn("survive_calamity", content)
        self.assertIn("watch_champion_rise", content)
        self.assertIn("support_gate", content)
        self.assertIn("support gate visual", content)
        self.assertIn("flash success", content)
        self.assertIn("stabilize gate", content)
        self.assertIn("gate_support", content)
        self.assertIn("survival", content)
        self.assertIn("champion", content)
        self.assertIn("observation-only", content)
        self.assertIn("hud modes", content)
        self.assertIn("f1", content)
        self.assertIn("tab", content)
        self.assertIn("restart run", content)
        self.assertIn("objective selection", content)
        self.assertIn("next objective", content)
        self.assertIn("result panel", content)
        self.assertIn("pagedown", content)
        self.assertIn("help panel", content)
        self.assertIn("f2", content)
        self.assertIn("e", content)
        self.assertIn("gate support accepted", content)
        self.assertIn("gate unavailable", content)
        self.assertIn("cooldown", content)
        self.assertIn("objective panel", content)
        self.assertIn("debug compact mode", content)
        self.assertIn("f3", content)

    def test_magic_system_has_second_spell(self):
        content = (GAME3D / "scripts" / "magic" / "MagicSystem.gd").read_text(encoding="utf-8")
        self.assertIn("func try_cast_nova", content)
        self.assertIn('register_cast(caster, null, "nova")', content)
        self.assertIn("func try_cast_control", content)
        self.assertIn('register_cast(caster, target, "control")', content)

    def test_world_manager_has_poi(self):
        content = (GAME3D / "scripts" / "world" / "WorldManager.gd").read_text(encoding="utf-8")
        self.assertIn('"name": "camp"', content)
        self.assertIn('"name": "ruins"', content)
        self.assertIn('"name": "rift_gate"', content)
        self.assertIn("get_poi_guidance", content)
        self.assertIn("get_neutral_gate_guidance", content)
        self.assertIn("neutral_gate_open_duration", content)
        self.assertIn("neutral_gate_opened", content)
        self.assertIn("neutral_gate_closed", content)
        self.assertIn("neutral_gate_breach", content)
        self.assertIn("update_poi_runtime", content)
        self.assertIn("trigger_poi_entry_effect", content)
        self.assertIn("domination_changed", content)
        self.assertIn("poi_influence_activation_time", content)
        self.assertIn("get_active_poi_influences", content)
        self.assertIn("influence_activated", content)
        self.assertIn("poi_structure_activation_time", content)
        self.assertIn("poi_structure_loss_time", content)
        self.assertIn("structure_established", content)
        self.assertIn("structure_lost", content)
        self.assertIn("StructureHalo", content)
        self.assertIn("poi_raid_duration", content)
        self.assertIn("get_raid_guidance", content)
        self.assertIn("raid_started", content)
        self.assertIn("raid_ended", content)
        self.assertIn("get_active_allegiances", content)
        self.assertIn("resolve_actor_allegiance", content)
        self.assertIn("allegiance_created", content)
        self.assertIn("allegiance_removed", content)
        self.assertIn("set_raid_pressure_modifiers", content)
        self.assertIn("set_world_event_visual", content)
        self.assertIn("set_support_gate_objective_visual", content)
        self.assertIn("support_gate_objective_visual_state", content)
        self.assertIn("set_location_templates", content)
        self.assertIn("set_bounty_state", content)
        self.assertIn("get_bounty_guidance", content)
        self.assertIn("set_convergence_state", content)
        self.assertIn("get_convergence_guidance", content)
        self.assertIn("ALLEGIANCE_DOCTRINES", content)
        self.assertIn("get_allegiance_doctrine", content)
        self.assertIn("get_allegiance_doctrine_modifiers", content)
        self.assertIn("get_allegiance_doctrine_project_bias", content)
        self.assertIn("get_allegiance_doctrine_vendetta_bias", content)
        self.assertIn("set_doctrine_templates", content)
        self.assertIn("ALLEGIANCE_PROJECT_TYPES", content)
        self.assertIn("get_allegiance_project", content)
        self.assertIn("get_allegiance_project_modifiers", content)
        self.assertIn("_update_allegiance_projects_runtime", content)
        self.assertIn("get_allegiance_vendetta_target", content)
        self.assertIn("get_allegiance_vendetta_modifiers", content)
        self.assertIn("register_vendetta_incident", content)
        self.assertIn("vendetta_started", content)
        self.assertIn("vendetta_resolved", content)
        self.assertIn("vendetta_expired", content)
        self.assertIn("set_allegiance_recovery_defense_modifiers", content)
        self.assertIn("get_allegiance_recovery_defense_delta", content)
        self.assertIn("set_mending_state", content)
        self.assertIn("get_allegiance_mending_modifiers", content)
        self.assertIn("set_alert_state", content)
        self.assertIn("get_alert_guidance", content)
        self.assertIn("get_alert_expedition_start_multiplier", content)
        self.assertIn("set_sanctuary_bastion_state", content)
        self.assertIn("get_sanctuary_bastion_guidance", content)
        self.assertIn("set_taboo_state", content)
        self.assertIn("get_taboo_avoidance_guidance", content)

    def test_debug_overlay_has_poi_status_labels(self):
        content = (GAME3D / "scripts" / "ui" / "DebugOverlay.gd").read_text(encoding="utf-8")
        self.assertIn("domine_humains", content)
        self.assertIn("domine_monstres", content)
        self.assertIn("conteste", content)
        self.assertIn("POI influence", content)
        self.assertIn("influence:off", content)
        self.assertIn("structure:off", content)
        self.assertIn("POI structures:", content)
        self.assertIn("Raid: active=", content)
        self.assertIn("raid:source", content)
        self.assertIn("Allegiances:", content)
        self.assertIn("allegiance:none", content)
        self.assertIn("Champions:", content)
        self.assertIn("Special arrivals:", content)
        self.assertIn("Rally:", content)
        self.assertIn("World Event:", content)
        self.assertIn("Relics:", content)
        self.assertIn("Relic carriers:", content)
        self.assertIn("Bounty:", content)
        self.assertIn("Bounty events:", content)
        self.assertIn("Renown:", content)
        self.assertIn("Notoriety:", content)
        self.assertIn("Top renown figures:", content)
        self.assertIn("Top notoriety figures:", content)
        self.assertIn("Neutral Gate:", content)
        self.assertIn("Support gate visual:", content)
        self.assertIn("Gate Responses:", content)
        self.assertIn("gate:open", content)
        self.assertIn("Doctrines:", content)
        self.assertIn("Doctrine dominant:", content)
        self.assertIn("Doctrine bias avg:", content)
        self.assertIn("Doctrine effects:", content)
        self.assertIn("Doctrine fallback map:", content)
        self.assertIn("const OVERLAY_MODE_PLAYER", content)
        self.assertIn("const OVERLAY_MODE_DEBUG", content)
        self.assertIn("const OVERLAY_MODE_OFF", content)
        self.assertIn("func set_overlay_mode", content)
        self.assertIn("func get_overlay_mode", content)
        self.assertIn("func toggle_debug_compact_mode", content)
        self.assertIn("func get_debug_compact_mode", content)
        self.assertIn("func cycle_overlay_mode", content)
        self.assertIn("var _help_panel_visible: bool", content)
        self.assertIn("var _debug_compact_mode: bool", content)
        self.assertIn("func toggle_help_panel", content)
        self.assertIn("func _build_help_panel_lines", content)
        self.assertIn("func _build_objective_panel_lines", content)
        self.assertIn("func _build_objective_interaction_feedback_line", content)
        self.assertIn("func _build_debug_compact_overlay_lines", content)
        self.assertIn("func _build_run_result_panel_lines", content)
        self.assertIn("_build_player_overlay_lines", content)
        self.assertIn("func _build_controls_help_lines", content)
        self.assertIn("KEY_F1", content)
        self.assertIn("KEY_TAB", content)
        self.assertIn("KEY_H", content)
        self.assertIn("KEY_F2", content)
        self.assertIn("KEY_F3", content)
        self.assertIn("HUD: F1/Tab toggle player-debug", content)
        self.assertIn("F1/Tab: HUD debug/player", content)
        self.assertIn("Debug detail:", content)
        self.assertIn("debug_full", content)
        self.assertIn("mode=debug_compact", content)
        self.assertIn("H/F2: help", content)
        self.assertIn("R: restart run", content)
        self.assertIn("O/PageDown: next objective", content)
        self.assertIn("RUN COMPLETED", content)
        self.assertIn("RUN FAILED", content)
        self.assertIn("====================", content)
        self.assertIn("Objective Panel", content)
        self.assertIn("HUD player", content)
        self.assertIn("Objective:", content)
        self.assertIn("Goal:", content)
        self.assertIn("Objective progress:", content)
        self.assertIn("Objective description:", content)
        self.assertIn("Objective config:", content)
        self.assertIn("Objective target:", content)
        self.assertIn("Objective status:", content)
        self.assertIn("Objective available:", content)
        self.assertIn("Objective interaction:", content)
        self.assertIn("E: support objective", content)
        self.assertIn("Objective interaction command:", content)
        self.assertIn("Support:", content)
        self.assertIn("Interaction:", content)
        self.assertIn("type=", content)
        self.assertIn("label=", content)
        self.assertIn("Objective fail reason:", content)
        self.assertIn("Objective result:", content)
        self.assertIn("Run status:", content)
        self.assertIn("run_status", content)
        self.assertIn("run_result_title", content)
        self.assertIn("run_result_lines", content)
        self.assertIn("run_result_visible", content)
        self.assertIn("RUN COMPLETED", content)
        self.assertIn("RUN FAILED", content)
        self.assertIn("Progress:", content)
        self.assertIn("Fail reason:", content)
        self.assertIn("objective_elapsed", content)
        self.assertIn("objective_required", content)
        self.assertIn("objective_fail_reason", content)
        self.assertIn("objective_dominant_faction", content)
        self.assertIn("objective_switch_count", content)
        self.assertIn("objective_description", content)
        self.assertIn("objective_category", content)
        self.assertIn("objective_config_label", content)
        self.assertIn("objective_available_ids", content)
        self.assertIn("objective_selected_index", content)
        self.assertIn("objective_available_count", content)
        self.assertIn("Objective selection:", content)
        self.assertIn("objective_completion_target_label", content)
        self.assertIn('"player"', content)
        self.assertIn('"debug"', content)
        self.assertIn('"off"', content)
        self.assertIn("run_summary_title", content)
        self.assertIn('lines.append("%s:" % run_summary_title)', content)
        self.assertIn("Run Summary:", content)
        self.assertIn("Timeline: recent=", content)
        self.assertIn("Timeline:", content)
        self.assertIn("Doctrine map:", content)
        self.assertIn("Projects:", content)
        self.assertIn("Project map:", content)
        self.assertIn("Vendettas:", content)
        self.assertIn("Vendetta map:", content)
        self.assertIn("Crisis:", content)
        self.assertIn("Crisis map:", content)
        self.assertIn("Recovery:", content)
        self.assertIn("Recovery map:", content)
        self.assertIn("Mending:", content)
        self.assertIn("Mending arcs:", content)
        self.assertIn("Oaths:", content)
        self.assertIn("Oath labels:", content)
        self.assertIn("Echoes:", content)
        self.assertIn("Echo labels:", content)
        self.assertIn("Expeditions:", content)
        self.assertIn("Expedition labels:", content)
        self.assertIn("Alerts:", content)
        self.assertIn("Alert labels:", content)
        self.assertIn("Sanctuaries/Bastions:", content)
        self.assertIn("Sanctuary/Bastion labels:", content)
        self.assertIn("Taboos:", content)
        self.assertIn("Taboo labels:", content)
        self.assertIn("Legacy:", content)
        self.assertIn("Legacy successors:", content)
        self.assertIn("Memorial/Scar:", content)
        self.assertIn("Memorial/Scar sites:", content)
        self.assertIn("Destiny:", content)
        self.assertIn("Destiny pulls:", content)
        self.assertIn("Convergence:", content)
        self.assertIn("Convergence zones:", content)
        self.assertIn("Marked zones:", content)
        self.assertIn("Marked zone labels:", content)
        self.assertIn("Rivalries:", content)
        self.assertIn("Rival pairs:", content)
        self.assertIn("Bonds:", content)
        self.assertIn("Bond links:", content)
        self.assertIn("Splinters:", content)
        self.assertIn("Splinter groups:", content)

    def test_sandbox_has_ranged_spawn_ratio(self):
        content = (GAME3D / "scripts" / "sandbox" / "SandboxSystems.gd").read_text(encoding="utf-8")
        self.assertIn("ranged_spawn_ratio", content)
        self.assertIn("RangedMonster.new()", content)

    def test_ai_has_ranged_reposition_logic(self):
        content = (GAME3D / "scripts" / "ai" / "AgentAI.gd").read_text(encoding="utf-8")
        self.assertIn("ranged_monster", content)
        self.assertIn('"state": "reposition"', content)
        self.assertIn('"state": "cast_control"', content)
        self.assertIn("magic_usage_bias", content)
        self.assertIn("control_usage_bias", content)
        self.assertIn('"state": "rally"', content)
        self.assertIn('"state": "raid"', content)
        self.assertIn("rally_regroup", content)
        self.assertIn("rally_renown_regroup", content)
        self.assertIn("rally_pressure", content)
        self.assertIn("raid_pressure", content)
        self.assertIn('"state": "hunt"', content)
        self.assertIn("get_bounty_guidance", content)
        self.assertIn("get_destiny_guidance", content)
        self.assertIn("destiny:", content)
        self.assertIn("get_rivalry_guidance", content)
        self.assertIn("rival_target", content)
        self.assertIn("get_convergence_guidance", content)
        self.assertIn("convergence_pull", content)
        self.assertIn("get_oath_guidance", content)
        self.assertIn("oath:guarding", content)
        self.assertIn("oath:seeking", content)
        self.assertIn("get_expedition_guidance", content)
        self.assertIn("expedition:", content)
        self.assertIn("get_alert_guidance", content)
        self.assertIn("alert:", content)
        self.assertIn("get_taboo_avoidance_guidance", content)
        self.assertIn("taboo:", content)
        self.assertIn("get_sanctuary_bastion_guidance", content)
        self.assertIn("sanctuary:", content)
        self.assertIn("bastion:", content)
        self.assertIn("get_allegiance_defense_guidance", content)
        self.assertIn("actor.allegiance_id", content)
        self.assertIn("notoriety_avoid", content)
        self.assertIn("_find_notoriety_focus_enemy", content)

    def test_human_agent_has_roles(self):
        content = (GAME3D / "scripts" / "entities" / "HumanAgent.gd").read_text(encoding="utf-8")
        self.assertIn('assign_role(role: String)', content)
        self.assertIn('"fighter"', content)
        self.assertIn('"mage"', content)
        self.assertIn('"scout"', content)

    def test_sandbox_assigns_human_roles(self):
        content = (GAME3D / "scripts" / "sandbox" / "SandboxSystems.gd").read_text(encoding="utf-8")
        self.assertIn("fighter_role_ratio", content)
        self.assertIn("mage_role_ratio", content)
        self.assertIn("scout_role_ratio", content)
        self.assertIn("assign_role(_pick_human_role())", content)

    def test_actor_has_progression_fields(self):
        content = (GAME3D / "scripts" / "entities" / "Actor.gd").read_text(encoding="utf-8")
        self.assertIn("var progress_xp: float", content)
        self.assertIn("var level: int", content)
        self.assertIn("var max_level: int", content)
        self.assertIn("award_progress_xp", content)
        self.assertIn("_check_level_up", content)
        self.assertIn("var kill_count: int", content)
        self.assertIn("var is_champion: bool", content)
        self.assertIn("champion_tag()", content)
        self.assertIn("is_ready_for_champion", content)
        self.assertIn("promote_to_champion", content)
        self.assertIn("rally_leader_id", content)
        self.assertIn("rally_bonus_active", content)
        self.assertIn('"rally":', content)
        self.assertIn("allegiance_id", content)
        self.assertIn("home_poi", content)
        self.assertIn("set_allegiance", content)
        self.assertIn("allegiance_tag", content)
        self.assertIn("special_arrival_id", content)
        self.assertIn("special_tag", content)
        self.assertIn("is_special_arrival", content)
        self.assertIn("apply_special_arrival_bonus", content)
        self.assertIn("relic_id", content)
        self.assertIn("relic_tag", content)
        self.assertIn("has_relic", content)
        self.assertIn("set_relic", content)
        self.assertIn("clear_relic", content)
        self.assertIn("bounty_marked", content)
        self.assertIn("set_bounty_marked", content)
        self.assertIn("bounty_tag", content)
        self.assertIn("destiny_active", content)
        self.assertIn("set_destiny_pull", content)
        self.assertIn("get_destiny_guidance", content)
        self.assertIn("destiny_tag", content)
        self.assertIn("oath_active", content)
        self.assertIn("set_oath_state", content)
        self.assertIn("get_oath_guidance", content)
        self.assertIn("oath_tag", content)
        self.assertIn("expedition_active", content)
        self.assertIn("set_expedition_state", content)
        self.assertIn("get_expedition_guidance", content)
        self.assertIn("expedition_tag", content)
        self.assertIn("rivalry_active", content)
        self.assertIn("set_rivalry_state", content)
        self.assertIn("get_rivalry_guidance", content)
        self.assertIn("rivalry_tag", content)
        self.assertIn("bond_patron_active", content)
        self.assertIn("set_bond_state", content)
        self.assertIn("bond_tag", content)
        self.assertIn("splinter_active", content)
        self.assertIn("set_splinter_state", content)
        self.assertIn("splinter_tag", content)
        self.assertIn("var renown: float", content)
        self.assertIn("var notoriety: float", content)
        self.assertIn("add_renown", content)
        self.assertIn("add_notoriety", content)
        self.assertIn("decay_notability", content)
        self.assertIn("renown_tag", content)
        self.assertIn("notoriety_tag", content)
        self.assertIn("can_lead_rally", content)

    def test_game_loop_exposes_progression_runtime_metrics(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("const XP_ON_HIT", content)
        self.assertIn("const XP_ON_CAST", content)
        self.assertIn("const XP_ON_KILL", content)
        self.assertIn("register_level_up", content)
        self.assertIn('"level_counts"', content)
        self.assertIn('"level_ups_total"', content)
        self.assertIn("avg_level", content)

    def test_game_loop_exposes_poi_influence_runtime_metrics(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("POI_INFLUENCE_ENERGY_REGEN_PER_SEC", content)
        self.assertIn("POI_INFLUENCE_XP_GAIN", content)
        self.assertIn("_apply_poi_influences", content)
        self.assertIn("poi_influence_activation_events_total", content)
        self.assertIn("poi_influence_xp_grants_total", content)
        self.assertIn("POI_STRUCTURE_EXTRA_ENERGY_REGEN_PER_SEC", content)
        self.assertIn("poi_structure_established_total", content)
        self.assertIn("poi_structure_lost_total", content)
        self.assertIn("raid_started_total", content)
        self.assertIn("raid_success_total", content)
        self.assertIn("allegiance_created_total", content)
        self.assertIn("allegiance_assignments_total", content)
        self.assertIn("_update_actor_allegiances", content)

    def test_game_loop_has_champion_metrics_and_promotion_hooks(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("CHAMPION_MIN_LEVEL", content)
        self.assertIn("CHAMPION_MIN_KILLS", content)
        self.assertIn("CHAMPION_MAX_RATIO", content)
        self.assertIn("champion_promotions_total", content)
        self.assertIn("_try_promote_champion", content)
        self.assertIn("_scan_for_champion_promotion", content)
        self.assertIn('"champion_alive_total"', content)
        self.assertIn("rally_groups_formed_total", content)
        self.assertIn("rally_followers_active", content)
        self.assertIn("_update_rally_runtime", content)

    def test_game_loop_has_world_event_scheduler_and_metrics(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("WORLD_EVENT_TYPES", content)
        self.assertIn("_update_world_events", content)
        self.assertIn("World Event START", content)
        self.assertIn("World Event END", content)
        self.assertIn('"world_event_active_id"', content)
        self.assertIn('"world_event_started_total"', content)
        self.assertIn("get_magic_modifiers", content)
        self.assertIn("get_melee_damage_multiplier", content)
        self.assertIn("get_speed_multiplier", content)
        self.assertIn("get_energy_regen_bonus_per_sec", content)

    def test_game_loop_has_special_arrival_scheduler_and_metrics(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("SPECIAL_ARRIVAL_COOLDOWN", content)
        self.assertIn("SPECIAL_ARRIVAL_MAX_ACTIVE", content)
        self.assertIn("_update_special_arrivals", content)
        self.assertIn("_collect_special_arrival_candidates", content)
        self.assertIn("Special Arrival START", content)
        self.assertIn("Special Arrival FALLEN", content)
        self.assertIn('"special_arrivals_active_total"', content)
        self.assertIn('"special_arrivals_total"', content)
        self.assertIn("_count_alive_special_arrivals", content)

    def test_game_loop_has_relic_scheduler_and_metrics(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("RELIC_COOLDOWN", content)
        self.assertIn("RELIC_TYPES", content)
        self.assertIn("_update_relic_system", content)
        self.assertIn("_collect_relic_candidates", content)
        self.assertIn("Relic APPEAR", content)
        self.assertIn("Relic ACQUIRED", content)
        self.assertIn("Relic LOST", content)
        self.assertIn('"relic_active_total"', content)
        self.assertIn('"relic_appear_total"', content)
        self.assertIn("_count_alive_relic_carriers", content)

    def test_game_loop_has_bounty_scheduler_and_metrics(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("BOUNTY_COOLDOWN", content)
        self.assertIn("BOUNTY_MAX_ACTIVE", content)
        self.assertIn("_update_bounty_system", content)
        self.assertIn("_pick_bounty_target", content)
        self.assertIn("Bounty START", content)
        self.assertIn("Bounty CLEARED", content)
        self.assertIn("Bounty EXPIRED", content)
        self.assertIn("DESTINY_TRIGGER_CHANCE", content)
        self.assertIn("_update_destiny_pulls", content)
        self.assertIn("Destiny START", content)
        self.assertIn("Destiny END", content)
        self.assertIn("Destiny FULFILLED", content)
        self.assertIn("Destiny INTERRUPTED", content)
        self.assertIn('"destiny_active_total"', content)
        self.assertIn("CONVERGENCE_TRIGGER_CHANCE", content)
        self.assertIn("_update_convergence_events", content)
        self.assertIn("Convergence START", content)
        self.assertIn("Convergence END", content)
        self.assertIn("Convergence INTERRUPTED", content)
        self.assertIn('"convergence_active_total"', content)
        self.assertIn("MARKED_ZONE_TRIGGER_CHANCE", content)
        self.assertIn("_update_marked_zones", content)
        self.assertIn("Zone SANCTIFIED", content)
        self.assertIn("Zone CORRUPTED", content)
        self.assertIn("Zone FADED", content)
        self.assertIn('"marked_zone_active_total"', content)
        self.assertIn("RIVALRY_TRIGGER_CHANCE", content)
        self.assertIn("_update_rivalries", content)
        self.assertIn("Rivalry START", content)
        self.assertIn("Duel START", content)
        self.assertIn("Rivalry RESOLVED", content)
        self.assertIn("Rivalry END", content)
        self.assertIn('"rivalry_active_total"', content)
        self.assertIn("BOND_START_DELAY", content)
        self.assertIn("_update_bonds", content)
        self.assertIn("Bond START", content)
        self.assertIn("Bond END", content)
        self.assertIn("Bond BROKEN", content)
        self.assertIn('"bond_active_total"', content)
        self.assertIn('"bounty_active"', content)
        self.assertIn('"bounty_started_total"', content)
        self.assertIn("_grant_bounty_clear_reward", content)
        self.assertIn("BOUNTY_NOTORIETY_PRIORITY_MIN", content)
        self.assertIn("Renown Rising", content)
        self.assertIn("Notoriety Rising", content)
        self.assertIn('"avg_renown"', content)
        self.assertIn('"avg_notoriety"', content)
        self.assertIn('"top_renown_labels"', content)
        self.assertIn('"top_notoriety_labels"', content)
        self.assertIn("Dungeon/Gate OPEN", content)
        self.assertIn("Dungeon/Gate CLOSED", content)
        self.assertIn("Dungeon/Gate BREACH", content)
        self.assertIn("Gate Response START", content)
        self.assertIn("Gate Response END", content)
        self.assertIn("Gate Response SUCCESS", content)
        self.assertIn("Gate Response INTERRUPTED", content)
        self.assertIn("MAX_MAJOR_EVENT_TIMELINE", content)
        self.assertIn("WORLD_OBJECTIVE_ID_OBSERVE_DOMINANCE", content)
        self.assertIn("WORLD_OBJECTIVE_ID_SURVIVE_CALAMITY", content)
        self.assertIn("WORLD_OBJECTIVE_ID_WATCH_CHAMPION_RISE", content)
        self.assertIn("WORLD_OBJECTIVE_ID_SUPPORT_GATE", content)
        self.assertIn('"category": "survival"', content)
        self.assertIn('"category": "champion"', content)
        self.assertIn('"category": "gate_support"', content)
        self.assertIn("OBJECTIVE_DOMINANCE_REQUIRED_TIME", content)
        self.assertIn("OBJECTIVE_FAIL_DEATHS_THRESHOLD", content)
        self.assertIn("OBJECTIVE_FAIL_SWITCH_THRESHOLD", content)
        self.assertIn("OBJECTIVE_GATE_SUPPORT_REQUIRED_ACTIONS", content)
        self.assertIn("OBJECTIVE_GATE_SUPPORT_INTERACTION_COOLDOWN", content)
        self.assertIn("major_event_timeline", content)
        self.assertIn("world_objective_status", content)
        self.assertIn("world_objective_progress", content)
        self.assertIn("world_objective_fail_reason", content)
        self.assertIn("world_objective_elapsed", content)
        self.assertIn("world_objective_required", content)
        self.assertIn("world_objective_dominant_faction", content)
        self.assertIn("world_objective_dominance_switches", content)
        self.assertIn("world_objective_description", content)
        self.assertIn("world_objective_category", content)
        self.assertIn("world_objective_config_label", content)
        self.assertIn("world_objective_available_ids", content)
        self.assertIn("world_objective_completion_target_label", content)
        self.assertIn("run_status", content)
        self.assertIn("run_result_title", content)
        self.assertIn("run_result_lines", content)
        self.assertIn("run_result_visible", content)
        self.assertIn("run_project_started_baseline", content)
        self.assertIn("run_vendetta_started_baseline", content)
        self.assertIn("run_vendetta_resolved_baseline", content)
        self.assertIn("func _record_major_event", content)
        self.assertIn("func _format_major_event_label", content)
        self.assertIn("func _trim_major_event_timeline", content)
        self.assertIn("func _capture_run_metrics_baseline", content)
        self.assertIn("func _get_available_world_objective_ids", content)
        self.assertIn("func _get_world_objective_definition", content)
        self.assertIn(
            "func _setup_world_objective(objective_id: String = WORLD_OBJECTIVE_ID_OBSERVE_DOMINANCE)",
            content
        )
        self.assertIn("func set_world_objective", content)
        self.assertIn("func cycle_world_objective", content)
        self.assertIn("func restart_run", content)
        self.assertIn("_setup_world_objective(restart_objective_id)", content)
        self.assertIn("event_log.clear()", content)
        self.assertIn("major_event_timeline.clear()", content)
        self.assertIn("func _set_objective_interaction_feedback", content)
        self.assertIn("func _update_objective_interaction_feedback", content)
        self.assertIn("func _push_support_gate_objective_visual_state", content)
        self.assertIn("func _update_support_gate_objective_visual_state", content)
        self.assertIn("world_manager.set_support_gate_objective_visual", content)
        self.assertIn("KEY_R", content)
        self.assertIn("KEY_O", content)
        self.assertIn("KEY_PAGEDOWN", content)
        self.assertIn("KEY_E", content)
        self.assertIn("func trigger_world_objective_interaction", content)
        self.assertIn("func _update_world_objective", content)
        self.assertIn("func _update_objective_dominance", content)
        self.assertIn("func _update_objective_survival", content)
        self.assertIn("func _update_objective_champion", content)
        self.assertIn("func _update_objective_gate_support", content)
        self.assertIn("func _compute_objective_dominant_faction", content)
        self.assertIn("func _set_run_result_from_objective", content)
        self.assertIn("func get_run_narrative_summary", content)
        self.assertIn('"neutral_gate_status"', content)
        self.assertIn('"neutral_gate_opened_total"', content)
        self.assertIn('"gate_response_started_total"', content)
        self.assertIn("Crisis START", content)
        self.assertIn("Crisis END", content)
        self.assertIn("Crisis RESOLVED", content)
        self.assertIn("Crisis EXPIRED", content)
        self.assertIn('"crisis_started_total"', content)
        self.assertIn("Recovery START", content)
        self.assertIn("Recovery END", content)
        self.assertIn("Recovery INTERRUPTED", content)
        self.assertIn('"recovery_started_total"', content)
        self.assertIn("Doctrine assigned", content)
        self.assertIn("Doctrine fallback used", content)
        self.assertIn("Doctrine ignored", content)
        self.assertIn('"allegiance_doctrine_counts"', content)
        self.assertIn('"allegiance_doctrine_source_counts"', content)
        self.assertIn('"allegiance_doctrine_average_biases"', content)
        self.assertIn('"doctrine_project_bias_counts"', content)
        self.assertIn('"doctrine_vendetta_bias_avg"', content)
        self.assertIn('"allegiance_doctrine_fallback_used_count"', content)
        self.assertIn('"allegiance_doctrine_dominant_id"', content)
        self.assertIn('"doctrine_templates_source"', content)
        self.assertIn('"doctrine_assigned_total"', content)
        self.assertIn('"narrative_timeline_labels"', content)
        self.assertIn('"narrative_timeline_count"', content)
        self.assertIn('"last_major_event_label"', content)
        self.assertIn('"run_summary_title"', content)
        self.assertIn('"run_summary_lines"', content)
        self.assertIn('"dominant_faction"', content)
        self.assertIn('"dominant_doctrine"', content)
        self.assertIn('"run_status"', content)
        self.assertIn('"run_result_title"', content)
        self.assertIn('"run_result_lines"', content)
        self.assertIn('"run_result_visible"', content)
        self.assertIn('"objective_active"', content)
        self.assertIn('"objective_id"', content)
        self.assertIn('"objective_title"', content)
        self.assertIn('"objective_description"', content)
        self.assertIn('"objective_category"', content)
        self.assertIn('"objective_config_label"', content)
        self.assertIn('"objective_available_ids"', content)
        self.assertIn('"objective_selected_index"', content)
        self.assertIn('"objective_available_count"', content)
        self.assertIn('"objective_completion_target_label"', content)
        self.assertIn('"objective_status"', content)
        self.assertIn('"objective_progress"', content)
        self.assertIn('"objective_elapsed"', content)
        self.assertIn('"objective_required"', content)
        self.assertIn('"objective_fail_reason"', content)
        self.assertIn('"objective_dominant_faction"', content)
        self.assertIn('"objective_switch_count"', content)
        self.assertIn('"objective_progress_label"', content)
        self.assertIn('"objective_result_label"', content)
        self.assertIn('"objective_interaction_count"', content)
        self.assertIn('"objective_interaction_required"', content)
        self.assertIn('"objective_interaction_label"', content)
        self.assertIn('"objective_interaction_available"', content)
        self.assertIn('"objective_interaction_cooldown"', content)
        self.assertIn('"objective_interaction_feedback_label"', content)
        self.assertIn('"objective_interaction_feedback_type"', content)
        self.assertIn('"objective_interaction_feedback_timer"', content)
        self.assertIn('"support_gate_visual_state"', content)
        self.assertIn('"support_gate_visual_label"', content)
        self.assertIn('"major_event_count"', content)
        self.assertIn('"project_count"', content)
        self.assertIn('"vendetta_count"', content)
        self.assertIn('"champion_count"', content)
        self.assertIn('"relic_count"', content)
        self.assertIn('"legacy_count"', content)
        self.assertIn('"doctrine_assigned"', content)
        self.assertIn('"objective_started"', content)
        self.assertIn('"objective_selected"', content)
        self.assertIn('"objective_interaction"', content)
        self.assertIn('"objective_completed"', content)
        self.assertIn('"objective_failed"', content)
        self.assertIn('"run_completed"', content)
        self.assertIn('"run_failed"', content)
        self.assertIn('"run_restarted"', content)
        self.assertIn("Objective START", content)
        self.assertIn("Objective SELECTED", content)
        self.assertIn("Objective INTERACTION", content)
        self.assertIn("Gate support accepted", content)
        self.assertIn("objective non-interactive", content)
        self.assertIn("gate unavailable", content)
        self.assertIn("cooldown", content)
        self.assertIn("Objective COMPLETE", content)
        self.assertIn("Objective FAILED", content)
        self.assertIn("Run COMPLETED", content)
        self.assertIn("Run FAILED", content)
        self.assertIn("Run RESTARTED", content)
        self.assertIn("world_objective_fail_reason = \"too_many_deaths\"", content)
        self.assertIn("world_objective_fail_reason = \"dominance_too_unstable\"", content)
        self.assertIn("Objective COMPLETE: faction=", content)
        self.assertIn("Project START", content)
        self.assertIn('"project_started"', content)
        self.assertIn("Project doctrine bias", content)
        self.assertIn("Project END", content)
        self.assertIn("Project INTERRUPTED", content)
        self.assertIn('"allegiance_project_counts"', content)
        self.assertIn('"project_started_total"', content)
        self.assertIn("Vendetta START", content)
        self.assertIn('"vendetta_started"', content)
        self.assertIn("Vendetta doctrine", content)
        self.assertIn("Vendetta END", content)
        self.assertIn("Vendetta RESOLVED", content)
        self.assertIn("Vendetta EXPIRED", content)
        self.assertIn('"allegiance_vendetta_labels"', content)
        self.assertIn('"vendetta_started_total"', content)
        self.assertIn("Legacy Triggered", content)
        self.assertIn("Successor Chosen", content)
        self.assertIn("Legacy Faded", content)
        self.assertIn('"legacy_successor_labels"', content)
        self.assertIn('"legacy_triggered_total"', content)
        self.assertIn("Memorial/Scar BORN", content)
        self.assertIn("Memorial/Scar FADED", content)
        self.assertIn('"memorial_scar_active_total"', content)
        self.assertIn("Oath START", content)
        self.assertIn("Oath END", content)
        self.assertIn("Oath FULFILLED", content)
        self.assertIn("Oath BROKEN", content)
        self.assertIn('"oath_active_count"', content)
        self.assertIn("Echo START", content)
        self.assertIn("Echo END", content)
        self.assertIn("Echo FADED", content)
        self.assertIn('"echo_active_count"', content)
        self.assertIn("Expedition START", content)
        self.assertIn("Expedition ARRIVED", content)
        self.assertIn("Expedition END", content)
        self.assertIn("Expedition INTERRUPTED", content)
        self.assertIn('"expedition_active_count"', content)
        self.assertIn("ALERT_START_CHANCE_BASE", content)
        self.assertIn("_setup_alert_state", content)
        self.assertIn("_update_alert_pulses", content)
        self.assertIn("Alert START", content)
        self.assertIn("Alert END", content)
        self.assertIn('"alert_active_count"', content)
        self.assertIn("SANCTUARY_BASTION_TRIGGER_CHANCE", content)
        self.assertIn("_setup_sanctuary_bastion_state", content)
        self.assertIn("_update_sanctuary_bastions", content)
        self.assertIn("Sanctuary RISE", content)
        self.assertIn("Bastion RISE", content)
        self.assertIn("Sanctuary/Bastion FADE", content)
        self.assertIn('"sanctuary_bastion_active_total"', content)
        self.assertIn("TABOO_TRIGGER_CHANCE", content)
        self.assertIn("_setup_taboo_state", content)
        self.assertIn("_update_taboos", content)
        self.assertIn("Taboo RISE", content)
        self.assertIn("Taboo FADE", content)
        self.assertIn('"taboo_active_total"', content)


if __name__ == "__main__":
    unittest.main()
