from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
GAME3D = ROOT / "game3d"


class TestGame3DScaffold(unittest.TestCase):
    def test_required_files_exist(self):
        required = [
            GAME3D / "project.godot",
            GAME3D / "scenes" / "MainSandbox.tscn",
            GAME3D / "scripts" / "core" / "GameLoop.gd",
            GAME3D / "scripts" / "world" / "WorldManager.gd",
            GAME3D / "scripts" / "entities" / "Actor.gd",
            GAME3D / "scripts" / "entities" / "HumanAgent.gd",
            GAME3D / "scripts" / "entities" / "MonsterAgent.gd",
            GAME3D / "scripts" / "entities" / "BruteMonster.gd",
            GAME3D / "scripts" / "entities" / "RangedMonster.gd",
            GAME3D / "scripts" / "ai" / "AgentAI.gd",
            GAME3D / "scripts" / "combat" / "CombatSystem.gd",
            GAME3D / "scripts" / "magic" / "MagicSystem.gd",
            GAME3D / "scripts" / "sandbox" / "SandboxSystems.gd",
            GAME3D / "scripts" / "ui" / "DebugOverlay.gd",
        ]

        for path in required:
            self.assertTrue(path.exists(), f"Missing file: {path}")

    def test_project_targets_main_scene(self):
        content = (GAME3D / "project.godot").read_text(encoding="utf-8")
        self.assertIn('run/main_scene="res://scenes/MainSandbox.tscn"', content)

    def test_main_scene_wires_core_systems(self):
        content = (GAME3D / "scenes" / "MainSandbox.tscn").read_text(encoding="utf-8")
        required_fragments = [
            "scripts/core/GameLoop.gd",
            "scripts/world/WorldManager.gd",
            "scripts/combat/CombatSystem.gd",
            "scripts/magic/MagicSystem.gd",
            "scripts/sandbox/SandboxSystems.gd",
            "scripts/ui/DebugOverlay.gd",
        ]
        for fragment in required_fragments:
            self.assertIn(fragment, content)

    def test_readme_mentions_new_3d_direction(self):
        content = (ROOT / "README.md").read_text(encoding="utf-8").lower()
        self.assertIn("game3d", content)
        self.assertIn("legacy python", content)
        self.assertIn("poi", content)
        self.assertIn("nova", content)
        self.assertIn("brute", content)
        self.assertIn("ranged", content)
        self.assertIn("control", content)
        self.assertIn("slow", content)
        self.assertIn("fighter", content)
        self.assertIn("mage", content)
        self.assertIn("scout", content)
        self.assertIn("champion", content)
        self.assertIn("rally", content)
        self.assertIn("outpost", content)
        self.assertIn("lair", content)
        self.assertIn("structure", content)
        self.assertIn("raid", content)
        self.assertIn("allegiance", content)
        self.assertIn("world event", content)
        self.assertIn("mana surge", content)
        self.assertIn("monster frenzy", content)
        self.assertIn("sanctuary calm", content)
        self.assertIn("special arrival", content)
        self.assertIn("summoned hero", content)
        self.assertIn("calamity invader", content)
        self.assertIn("relic", content)
        self.assertIn("arcane sigil", content)
        self.assertIn("oath standard", content)
        self.assertIn("bounty", content)
        self.assertIn("marked target", content)
        self.assertIn("hunt", content)
        self.assertIn("renown", content)
        self.assertIn("notoriety", content)
        self.assertIn("rift gate", content)
        self.assertIn("dungeon/gate", content)
        self.assertIn("gate response", content)
        self.assertIn("gate_seal", content)
        self.assertIn("gate_exploit", content)
        self.assertIn("allegiance crisis", content)
        self.assertIn("recovery pulse", content)
        self.assertIn("doctrine", content)
        self.assertIn("ethos", content)
        self.assertIn("project", content)
        self.assertIn("fortify", content)
        self.assertIn("warband", content)
        self.assertIn("ritual", content)
        self.assertIn("vendetta", content)
        self.assertIn("grudge", content)
        self.assertIn("legacy", content)
        self.assertIn("succession", content)
        self.assertIn("successor", content)
        self.assertIn("memorial", content)
        self.assertIn("scar", content)
        self.assertIn("destiny", content)
        self.assertIn("convergence", content)
        self.assertIn("sanctified", content)
        self.assertIn("corrupted", content)
        self.assertIn("rivalry", content)
        self.assertIn("duel", content)
        self.assertIn("bond", content)
        self.assertIn("patron", content)
        self.assertIn("splinter", content)
        self.assertIn("breakaway", content)

    def test_magic_system_has_second_spell(self):
        content = (GAME3D / "scripts" / "magic" / "MagicSystem.gd").read_text(encoding="utf-8")
        self.assertIn("func try_cast_nova", content)
        self.assertIn('register_cast(caster, null, "nova")', content)
        self.assertIn("func try_cast_control", content)
        self.assertIn('register_cast(caster, target, "control")', content)

    def test_world_manager_has_poi(self):
        content = (GAME3D / "scripts" / "world" / "WorldManager.gd").read_text(encoding="utf-8")
        self.assertIn('"name": "camp"', content)
        self.assertIn('"name": "ruins"', content)
        self.assertIn('"name": "rift_gate"', content)
        self.assertIn("get_poi_guidance", content)
        self.assertIn("get_neutral_gate_guidance", content)
        self.assertIn("neutral_gate_open_duration", content)
        self.assertIn("neutral_gate_opened", content)
        self.assertIn("neutral_gate_closed", content)
        self.assertIn("neutral_gate_breach", content)
        self.assertIn("update_poi_runtime", content)
        self.assertIn("trigger_poi_entry_effect", content)
        self.assertIn("domination_changed", content)
        self.assertIn("poi_influence_activation_time", content)
        self.assertIn("get_active_poi_influences", content)
        self.assertIn("influence_activated", content)
        self.assertIn("poi_structure_activation_time", content)
        self.assertIn("poi_structure_loss_time", content)
        self.assertIn("structure_established", content)
        self.assertIn("structure_lost", content)
        self.assertIn("StructureHalo", content)
        self.assertIn("poi_raid_duration", content)
        self.assertIn("get_raid_guidance", content)
        self.assertIn("raid_started", content)
        self.assertIn("raid_ended", content)
        self.assertIn("get_active_allegiances", content)
        self.assertIn("resolve_actor_allegiance", content)
        self.assertIn("allegiance_created", content)
        self.assertIn("allegiance_removed", content)
        self.assertIn("set_raid_pressure_modifiers", content)
        self.assertIn("set_world_event_visual", content)
        self.assertIn("set_bounty_state", content)
        self.assertIn("get_bounty_guidance", content)
        self.assertIn("set_convergence_state", content)
        self.assertIn("get_convergence_guidance", content)
        self.assertIn("ALLEGIANCE_DOCTRINES", content)
        self.assertIn("get_allegiance_doctrine", content)
        self.assertIn("get_allegiance_doctrine_modifiers", content)
        self.assertIn("ALLEGIANCE_PROJECT_TYPES", content)
        self.assertIn("get_allegiance_project", content)
        self.assertIn("get_allegiance_project_modifiers", content)
        self.assertIn("_update_allegiance_projects_runtime", content)
        self.assertIn("get_allegiance_vendetta_target", content)
        self.assertIn("get_allegiance_vendetta_modifiers", content)
        self.assertIn("register_vendetta_incident", content)
        self.assertIn("vendetta_started", content)
        self.assertIn("vendetta_resolved", content)
        self.assertIn("vendetta_expired", content)
        self.assertIn("set_allegiance_recovery_defense_modifiers", content)
        self.assertIn("get_allegiance_recovery_defense_delta", content)

    def test_debug_overlay_has_poi_status_labels(self):
        content = (GAME3D / "scripts" / "ui" / "DebugOverlay.gd").read_text(encoding="utf-8")
        self.assertIn("domine_humains", content)
        self.assertIn("domine_monstres", content)
        self.assertIn("conteste", content)
        self.assertIn("POI influence", content)
        self.assertIn("influence:off", content)
        self.assertIn("structure:off", content)
        self.assertIn("POI structures:", content)
        self.assertIn("Raid: active=", content)
        self.assertIn("raid:source", content)
        self.assertIn("Allegiances:", content)
        self.assertIn("allegiance:none", content)
        self.assertIn("Champions:", content)
        self.assertIn("Special arrivals:", content)
        self.assertIn("Rally:", content)
        self.assertIn("World Event:", content)
        self.assertIn("Relics:", content)
        self.assertIn("Relic carriers:", content)
        self.assertIn("Bounty:", content)
        self.assertIn("Bounty events:", content)
        self.assertIn("Renown:", content)
        self.assertIn("Notoriety:", content)
        self.assertIn("Top renown figures:", content)
        self.assertIn("Top notoriety figures:", content)
        self.assertIn("Neutral Gate:", content)
        self.assertIn("Gate Responses:", content)
        self.assertIn("gate:open", content)
        self.assertIn("Doctrines:", content)
        self.assertIn("Doctrine map:", content)
        self.assertIn("Projects:", content)
        self.assertIn("Project map:", content)
        self.assertIn("Vendettas:", content)
        self.assertIn("Vendetta map:", content)
        self.assertIn("Crisis:", content)
        self.assertIn("Crisis map:", content)
        self.assertIn("Recovery:", content)
        self.assertIn("Recovery map:", content)
        self.assertIn("Legacy:", content)
        self.assertIn("Legacy successors:", content)
        self.assertIn("Memorial/Scar:", content)
        self.assertIn("Memorial/Scar sites:", content)
        self.assertIn("Destiny:", content)
        self.assertIn("Destiny pulls:", content)
        self.assertIn("Convergence:", content)
        self.assertIn("Convergence zones:", content)
        self.assertIn("Marked zones:", content)
        self.assertIn("Marked zone labels:", content)
        self.assertIn("Rivalries:", content)
        self.assertIn("Rival pairs:", content)
        self.assertIn("Bonds:", content)
        self.assertIn("Bond links:", content)
        self.assertIn("Splinters:", content)
        self.assertIn("Splinter groups:", content)

    def test_sandbox_has_ranged_spawn_ratio(self):
        content = (GAME3D / "scripts" / "sandbox" / "SandboxSystems.gd").read_text(encoding="utf-8")
        self.assertIn("ranged_spawn_ratio", content)
        self.assertIn("RangedMonster.new()", content)

    def test_ai_has_ranged_reposition_logic(self):
        content = (GAME3D / "scripts" / "ai" / "AgentAI.gd").read_text(encoding="utf-8")
        self.assertIn("ranged_monster", content)
        self.assertIn('"state": "reposition"', content)
        self.assertIn('"state": "cast_control"', content)
        self.assertIn("magic_usage_bias", content)
        self.assertIn("control_usage_bias", content)
        self.assertIn('"state": "rally"', content)
        self.assertIn('"state": "raid"', content)
        self.assertIn("rally_regroup", content)
        self.assertIn("rally_renown_regroup", content)
        self.assertIn("rally_pressure", content)
        self.assertIn("raid_pressure", content)
        self.assertIn('"state": "hunt"', content)
        self.assertIn("get_bounty_guidance", content)
        self.assertIn("get_destiny_guidance", content)
        self.assertIn("destiny:", content)
        self.assertIn("get_rivalry_guidance", content)
        self.assertIn("rival_target", content)
        self.assertIn("get_convergence_guidance", content)
        self.assertIn("convergence_pull", content)
        self.assertIn("get_allegiance_defense_guidance", content)
        self.assertIn("actor.allegiance_id", content)
        self.assertIn("notoriety_avoid", content)
        self.assertIn("_find_notoriety_focus_enemy", content)

    def test_human_agent_has_roles(self):
        content = (GAME3D / "scripts" / "entities" / "HumanAgent.gd").read_text(encoding="utf-8")
        self.assertIn('assign_role(role: String)', content)
        self.assertIn('"fighter"', content)
        self.assertIn('"mage"', content)
        self.assertIn('"scout"', content)

    def test_sandbox_assigns_human_roles(self):
        content = (GAME3D / "scripts" / "sandbox" / "SandboxSystems.gd").read_text(encoding="utf-8")
        self.assertIn("fighter_role_ratio", content)
        self.assertIn("mage_role_ratio", content)
        self.assertIn("scout_role_ratio", content)
        self.assertIn("assign_role(_pick_human_role())", content)

    def test_actor_has_progression_fields(self):
        content = (GAME3D / "scripts" / "entities" / "Actor.gd").read_text(encoding="utf-8")
        self.assertIn("var progress_xp: float", content)
        self.assertIn("var level: int", content)
        self.assertIn("var max_level: int", content)
        self.assertIn("award_progress_xp", content)
        self.assertIn("_check_level_up", content)
        self.assertIn("var kill_count: int", content)
        self.assertIn("var is_champion: bool", content)
        self.assertIn("champion_tag()", content)
        self.assertIn("is_ready_for_champion", content)
        self.assertIn("promote_to_champion", content)
        self.assertIn("rally_leader_id", content)
        self.assertIn("rally_bonus_active", content)
        self.assertIn('"rally":', content)
        self.assertIn("allegiance_id", content)
        self.assertIn("home_poi", content)
        self.assertIn("set_allegiance", content)
        self.assertIn("allegiance_tag", content)
        self.assertIn("special_arrival_id", content)
        self.assertIn("special_tag", content)
        self.assertIn("is_special_arrival", content)
        self.assertIn("apply_special_arrival_bonus", content)
        self.assertIn("relic_id", content)
        self.assertIn("relic_tag", content)
        self.assertIn("has_relic", content)
        self.assertIn("set_relic", content)
        self.assertIn("clear_relic", content)
        self.assertIn("bounty_marked", content)
        self.assertIn("set_bounty_marked", content)
        self.assertIn("bounty_tag", content)
        self.assertIn("destiny_active", content)
        self.assertIn("set_destiny_pull", content)
        self.assertIn("get_destiny_guidance", content)
        self.assertIn("destiny_tag", content)
        self.assertIn("rivalry_active", content)
        self.assertIn("set_rivalry_state", content)
        self.assertIn("get_rivalry_guidance", content)
        self.assertIn("rivalry_tag", content)
        self.assertIn("bond_patron_active", content)
        self.assertIn("set_bond_state", content)
        self.assertIn("bond_tag", content)
        self.assertIn("splinter_active", content)
        self.assertIn("set_splinter_state", content)
        self.assertIn("splinter_tag", content)
        self.assertIn("var renown: float", content)
        self.assertIn("var notoriety: float", content)
        self.assertIn("add_renown", content)
        self.assertIn("add_notoriety", content)
        self.assertIn("decay_notability", content)
        self.assertIn("renown_tag", content)
        self.assertIn("notoriety_tag", content)
        self.assertIn("can_lead_rally", content)

    def test_game_loop_exposes_progression_runtime_metrics(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("const XP_ON_HIT", content)
        self.assertIn("const XP_ON_CAST", content)
        self.assertIn("const XP_ON_KILL", content)
        self.assertIn("register_level_up", content)
        self.assertIn('"level_counts"', content)
        self.assertIn('"level_ups_total"', content)
        self.assertIn("avg_level", content)

    def test_game_loop_exposes_poi_influence_runtime_metrics(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("POI_INFLUENCE_ENERGY_REGEN_PER_SEC", content)
        self.assertIn("POI_INFLUENCE_XP_GAIN", content)
        self.assertIn("_apply_poi_influences", content)
        self.assertIn("poi_influence_activation_events_total", content)
        self.assertIn("poi_influence_xp_grants_total", content)
        self.assertIn("POI_STRUCTURE_EXTRA_ENERGY_REGEN_PER_SEC", content)
        self.assertIn("poi_structure_established_total", content)
        self.assertIn("poi_structure_lost_total", content)
        self.assertIn("raid_started_total", content)
        self.assertIn("raid_success_total", content)
        self.assertIn("allegiance_created_total", content)
        self.assertIn("allegiance_assignments_total", content)
        self.assertIn("_update_actor_allegiances", content)

    def test_game_loop_has_champion_metrics_and_promotion_hooks(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("CHAMPION_MIN_LEVEL", content)
        self.assertIn("CHAMPION_MIN_KILLS", content)
        self.assertIn("CHAMPION_MAX_RATIO", content)
        self.assertIn("champion_promotions_total", content)
        self.assertIn("_try_promote_champion", content)
        self.assertIn("_scan_for_champion_promotion", content)
        self.assertIn('"champion_alive_total"', content)
        self.assertIn("rally_groups_formed_total", content)
        self.assertIn("rally_followers_active", content)
        self.assertIn("_update_rally_runtime", content)

    def test_game_loop_has_world_event_scheduler_and_metrics(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("WORLD_EVENT_TYPES", content)
        self.assertIn("_update_world_events", content)
        self.assertIn("World Event START", content)
        self.assertIn("World Event END", content)
        self.assertIn('"world_event_active_id"', content)
        self.assertIn('"world_event_started_total"', content)
        self.assertIn("get_magic_modifiers", content)
        self.assertIn("get_melee_damage_multiplier", content)
        self.assertIn("get_speed_multiplier", content)
        self.assertIn("get_energy_regen_bonus_per_sec", content)

    def test_game_loop_has_special_arrival_scheduler_and_metrics(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("SPECIAL_ARRIVAL_COOLDOWN", content)
        self.assertIn("SPECIAL_ARRIVAL_MAX_ACTIVE", content)
        self.assertIn("_update_special_arrivals", content)
        self.assertIn("_collect_special_arrival_candidates", content)
        self.assertIn("Special Arrival START", content)
        self.assertIn("Special Arrival FALLEN", content)
        self.assertIn('"special_arrivals_active_total"', content)
        self.assertIn('"special_arrivals_total"', content)
        self.assertIn("_count_alive_special_arrivals", content)

    def test_game_loop_has_relic_scheduler_and_metrics(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("RELIC_COOLDOWN", content)
        self.assertIn("RELIC_TYPES", content)
        self.assertIn("_update_relic_system", content)
        self.assertIn("_collect_relic_candidates", content)
        self.assertIn("Relic APPEAR", content)
        self.assertIn("Relic ACQUIRED", content)
        self.assertIn("Relic LOST", content)
        self.assertIn('"relic_active_total"', content)
        self.assertIn('"relic_appear_total"', content)
        self.assertIn("_count_alive_relic_carriers", content)

    def test_game_loop_has_bounty_scheduler_and_metrics(self):
        content = (GAME3D / "scripts" / "core" / "GameLoop.gd").read_text(encoding="utf-8")
        self.assertIn("BOUNTY_COOLDOWN", content)
        self.assertIn("BOUNTY_MAX_ACTIVE", content)
        self.assertIn("_update_bounty_system", content)
        self.assertIn("_pick_bounty_target", content)
        self.assertIn("Bounty START", content)
        self.assertIn("Bounty CLEARED", content)
        self.assertIn("Bounty EXPIRED", content)
        self.assertIn("DESTINY_TRIGGER_CHANCE", content)
        self.assertIn("_update_destiny_pulls", content)
        self.assertIn("Destiny START", content)
        self.assertIn("Destiny END", content)
        self.assertIn("Destiny FULFILLED", content)
        self.assertIn("Destiny INTERRUPTED", content)
        self.assertIn('"destiny_active_total"', content)
        self.assertIn("CONVERGENCE_TRIGGER_CHANCE", content)
        self.assertIn("_update_convergence_events", content)
        self.assertIn("Convergence START", content)
        self.assertIn("Convergence END", content)
        self.assertIn("Convergence INTERRUPTED", content)
        self.assertIn('"convergence_active_total"', content)
        self.assertIn("MARKED_ZONE_TRIGGER_CHANCE", content)
        self.assertIn("_update_marked_zones", content)
        self.assertIn("Zone SANCTIFIED", content)
        self.assertIn("Zone CORRUPTED", content)
        self.assertIn("Zone FADED", content)
        self.assertIn('"marked_zone_active_total"', content)
        self.assertIn("RIVALRY_TRIGGER_CHANCE", content)
        self.assertIn("_update_rivalries", content)
        self.assertIn("Rivalry START", content)
        self.assertIn("Duel START", content)
        self.assertIn("Rivalry RESOLVED", content)
        self.assertIn("Rivalry END", content)
        self.assertIn('"rivalry_active_total"', content)
        self.assertIn("BOND_START_DELAY", content)
        self.assertIn("_update_bonds", content)
        self.assertIn("Bond START", content)
        self.assertIn("Bond END", content)
        self.assertIn("Bond BROKEN", content)
        self.assertIn('"bond_active_total"', content)
        self.assertIn('"bounty_active"', content)
        self.assertIn('"bounty_started_total"', content)
        self.assertIn("_grant_bounty_clear_reward", content)
        self.assertIn("BOUNTY_NOTORIETY_PRIORITY_MIN", content)
        self.assertIn("Renown Rising", content)
        self.assertIn("Notoriety Rising", content)
        self.assertIn('"avg_renown"', content)
        self.assertIn('"avg_notoriety"', content)
        self.assertIn('"top_renown_labels"', content)
        self.assertIn('"top_notoriety_labels"', content)
        self.assertIn("Dungeon/Gate OPEN", content)
        self.assertIn("Dungeon/Gate CLOSED", content)
        self.assertIn("Dungeon/Gate BREACH", content)
        self.assertIn("Gate Response START", content)
        self.assertIn("Gate Response END", content)
        self.assertIn("Gate Response SUCCESS", content)
        self.assertIn("Gate Response INTERRUPTED", content)
        self.assertIn('"neutral_gate_status"', content)
        self.assertIn('"neutral_gate_opened_total"', content)
        self.assertIn('"gate_response_started_total"', content)
        self.assertIn("Crisis START", content)
        self.assertIn("Crisis END", content)
        self.assertIn("Crisis RESOLVED", content)
        self.assertIn("Crisis EXPIRED", content)
        self.assertIn('"crisis_started_total"', content)
        self.assertIn("Recovery START", content)
        self.assertIn("Recovery END", content)
        self.assertIn("Recovery INTERRUPTED", content)
        self.assertIn('"recovery_started_total"', content)
        self.assertIn("Doctrine assigned", content)
        self.assertIn('"allegiance_doctrine_counts"', content)
        self.assertIn('"doctrine_assigned_total"', content)
        self.assertIn("Project START", content)
        self.assertIn("Project END", content)
        self.assertIn("Project INTERRUPTED", content)
        self.assertIn('"allegiance_project_counts"', content)
        self.assertIn('"project_started_total"', content)
        self.assertIn("Vendetta START", content)
        self.assertIn("Vendetta END", content)
        self.assertIn("Vendetta RESOLVED", content)
        self.assertIn("Vendetta EXPIRED", content)
        self.assertIn('"allegiance_vendetta_labels"', content)
        self.assertIn('"vendetta_started_total"', content)
        self.assertIn("Legacy Triggered", content)
        self.assertIn("Successor Chosen", content)
        self.assertIn("Legacy Faded", content)
        self.assertIn('"legacy_successor_labels"', content)
        self.assertIn('"legacy_triggered_total"', content)
        self.assertIn("Memorial/Scar BORN", content)
        self.assertIn("Memorial/Scar FADED", content)
        self.assertIn('"memorial_scar_active_total"', content)


if __name__ == "__main__":
    unittest.main()
